"""Guards how the project's Python version is declared.

Two files mention a Python version, and they mean different things:

``pyproject.toml`` ``project.requires-python``
    The public compatibility floor — the oldest Python a consumer may install on.
    This is the only Python version written by hand. Ruff infers its target version
    from it, and mypy follows the interpreter uv selects, so neither repeats it.

``.python-version``
    The interpreter used for local development and CI, generated by ``uv python pin``.
    Optional: uv resolves an interpreter from ``requires-python`` without it. It exists
    so a fresh clone does not silently drift onto a newer Python as new releases land.

These may legitimately differ — supporting ``>=3.14`` while developing on a newer
version is fine. What must hold is that the pin is not *below* the floor, and that
neither ruff nor mypy duplicates the number.
"""

import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _pyproject() -> dict[str, object]:
    return tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))


def _tool_table(name: str) -> dict[str, object]:
    tool = _pyproject().get("tool")
    assert isinstance(tool, dict)
    table = tool.get(name, {})
    assert isinstance(table, dict)
    return table


def _parse_version(text: str, *, source: str) -> tuple[int, int]:
    match = re.fullmatch(r"(\d+)\.(\d+)", text.strip())
    assert match is not None, (
        f"{source} must be written as 'MAJOR.MINOR' so it can be compared "
        f"mechanically; got {text.strip()!r}"
    )
    return int(match.group(1)), int(match.group(2))


def _requires_python_floor() -> tuple[int, int]:
    """Return the ``(major, minor)`` lower bound declared by ``requires-python``."""
    project = _pyproject().get("project")
    assert isinstance(project, dict)
    requirement = str(project["requires-python"]).strip()
    assert requirement.startswith(">="), (
        f"requires-python must be a '>=MAJOR.MINOR' floor; got {requirement!r}"
    )
    return _parse_version(requirement.removeprefix(">="), source="requires-python")


def _pinned_version() -> tuple[int, int] | None:
    """Return the ``.python-version`` pin, or ``None`` if the file is absent."""
    pin = ROOT / ".python-version"
    if not pin.is_file():
        return None
    return _parse_version(pin.read_text(encoding="utf-8"), source=".python-version")


class TestDeclaredVersionsAreConsistent:
    def test_pin_is_not_below_the_supported_floor(self) -> None:
        pinned = _pinned_version()
        if pinned is None:
            return  # No pin: uv resolves from requires-python, which is valid.
        assert pinned >= _requires_python_floor(), (
            ".python-version is below requires-python; run `uv python pin` with a "
            "version the project actually supports"
        )

    def test_running_interpreter_satisfies_the_supported_floor(self) -> None:
        assert sys.version_info[:2] >= _requires_python_floor(), (
            "this interpreter is older than requires-python — the .venv is probably "
            "stale; run `uv sync`"
        )


class TestVersionIsNotDuplicated:
    def test_ruff_does_not_pin_target_version(self) -> None:
        assert "target-version" not in _tool_table("ruff"), (
            "ruff must infer target-version from requires-python; remove the literal"
        )

    def test_mypy_does_not_pin_python_version(self) -> None:
        assert "python_version" not in _tool_table("mypy"), (
            "mypy must follow the uv-selected interpreter; remove the literal"
        )
